### ISSUE TITLE
Video Support? 😢

### ISSUE THREAD

**Issue by Tunakirkoc** [sawyerpollard/MineWeather#15]
That will be nice.

**Comment by GreatSymphonia** [comment]
We would need to implement a background video which would be a bit heavy to load for the less strong PC.  Maybe a high quality gif or something like that could do it.

**Comment by sawyerpollard** [comment]
I would be really interested in how quickly Chrome can load GIFs, as well as compression strategies for them.

**Comment by GreatSymphonia** [comment]
@Tunakirkoc I would ask you to follow the issue #9 for the 8k support
The problem with video is exactly the same as the problem with higher resolution pictures.
