### ISSUE TITLE
Night Pictures?

### ISSUE THREAD

**Issue by SunnyMonster123** [sawyerpollard/MineWeather#16]
It will be cool if, after sunset, the pictures turn into nighttime ones.

**Comment by GreatSymphonia** [comment]
Easily doable, could implement it once my localization pull request will be accepted.

**Comment by sawyerpollard** [comment]
Night mode is a top priority for me. I'm aiming to implement it this weekend. The hard part will be finding new night time images.

**Comment by rhld16** [comment]
And to append to this maybe it would be worth looking into some of the other weather conitions that openweathermap lists here: https://openweathermap.org/weather-conditions

**Comment by sawyerpollard** [comment]
I suppose I can close this issue now because the new version has a day, night, and twilight mode!
I hope you like it. I had to take new screenshots.

Here's the link: https://chrome.google.com/webstore/detail/mineweather/gklgaaagldobfcacmhhbnbgofohfgneb
