### ISSUE TITLE
Firefox extension download?

### ISSUE THREAD

**Issue by divadsn** [sawyerpollard/MineWeather#34]
Hey,

I noticed your listings were taken down by a DMCA from Mojang, could you provide a XPI file for manual install?

**Comment by sawyerpollard** [comment]
The Firefox extension is awaiting approval right now actually.

This will be the link once it's approved shortly: https://addons.mozilla.org/en-US/firefox/addon/mineweather/

I can try to release an XPI on GitHub soon too.
