### ISSUE TITLE
Way to give you some money

### ISSUE THREAD

**Issue by Xalaxis** [sawyerpollard/MineWeather#36]
Hi there Sawyer,

Loved this extension for a while, and so happy to see it back in time for Christmas with the new night images as well. Is there any way to drop you some money as a present? I appreciate you linked the shader and texture pack devs but I want to give _you_ something for developing the extension and taking the pictures themselves :)

**Comment by sawyerpollard** [comment]
Hi there! That's very generous of you! Thank you. I actually created a GitHub Sponsors profile which allows one time donations. Obviously, there's no expectation but thank you for your interest!

https://github.com/sponsors/sawyerpollard

**Comment by Xalaxis** [comment]
Sent you a late Christmas present. MineWeather really brings me joy every time I see my browser 🎅

**Comment by Zo-Bro-23** [comment]
> I appreciate you linked the shader and texture pack devs but I want to give _you_ something for developing the extension and taking the pictures themselves :)

I'm looking for the shader and texture packs used (#42), but I can't seem to find them. Where did you find these links?
