### ISSUE TITLE
infinite loading in Mineweather 0.4.3

### ISSUE THREAD

**Issue by tikkou** [sawyerpollard/MineWeather#38]
![image](https://user-images.githubusercontent.com/71342961/160222110-d2a46098-2cfc-45b4-9d80-9bd787f65996.png)

I'm in the beta channel for some months now and with the last windows update it updated a lot of apps (maybe edge too) since beta and dev channels were temporaly merged, I hope that this is just a windows dev channel fluke

edge version: 99.0.1150.52
windows 11 version: 22581.100 ni_release
MineWeather version: 0.4.1

**Comment by ratjohnson** [comment]
It might not be the windows update, but a thing with Mineweather itself. Currently having this problem as well and I'm using chrome.

**Comment by TheBanjo67** [comment]
Has anyone found a solution or reason for this yet?

**Comment by Phoenotic** [comment]
> Has anyone found a solution or reason for this yet?

@sawyerpollard, I think this is an issue regarding the new updates for Chromium-based browsers (Brave, Vivaldi, Edge, etc). Personally, I am using Brave, and the problem continues to persist.

**Comment by sawyerpollard** [comment]
Thank you everyone for the report.
Could you try using it again on Chrome or Edge and see if it works? I believe I had an account issue with the weather API service I'm using but may have fixed it. I'm still waiting to get the fix approved for Firefox.

Hope this helps!

**Comment by Phoenotic** [comment]
> Thank you everyone for the report. Could you try using it again on Chrome or Edge and see if it works? I believe I had an account issue with the weather API service I'm using but may have fixed it. I'm still waiting to get the fix approved for Firefox.
> 
> Hope this helps!

Hey, @sawyerpollard. Just checked Chrome, and it's working as usual (![image](https://user-images.githubusercontent.com/76280083/161188454-ef61e548-d529-4c5c-9322-76aff6c724d3.png)

Not sure what's going on with Brave, though, since the same problem is persisting on it.

**Comment by Phoenotic** [comment]
> Thank you everyone for the report. Could you try using it again on Chrome or Edge and see if it works? I believe I had an account issue with the weather API service I'm using but may have fixed it. I'm still waiting to get the fix approved for Firefox.
> 
> Hope this helps!

I uninstalled the extension, and that must've updated the code because now it works on all the browsers I am using. Seems like the issue is fixed. Well at least on Firebox, Chrome, and Brave.

**Comment by sawyerpollard** [comment]
I did notice today that occasionally it will load infinitely again. But when refreshing the page it instantly displays the weather. I will definitely investigate this further.

**Comment by tikkou** [comment]
it's working fine for me, also https://github.com/sawyerpollard/MineWeather/pull/40 pls
