### ISSUE TITLE
infinite loading in MineWeather 0.4.3

### ISSUE THREAD

**Issue by tikkou** [sawyerpollard/MineWeather#41]
![image](https://user-images.githubusercontent.com/71342961/193482121-c31d59bf-9f3b-485e-ad45-585118906869.png)

**Comment by echoreos** [comment]
same issue, dif message 
<img width="960" alt="infinite loading" src="https://user-images.githubusercontent.com/115434697/194785933-91a791da-c88a-42e5-a70d-6a74dcfbb098.png">

**Comment by tikkou** [comment]
not working again

**Comment by echoreos** [comment]
was working last night but not working again this afternoon. new error message in development window
<img width="960" alt="infiloading" src="https://user-images.githubusercontent.com/115434697/197267089-3e5e26af-7830-4106-8bd4-1c54801ff808.png">

**Comment by echoreos** [comment]
follow up to infi-loading issue. for some reason it doesnt work during the day, but every now and then at about 830p, EST/USA timezone it will work. and then refuse to work again after about half an hour. ive had this happen on multiple days so i think its related to the infi loading issue

**Comment by sawyerpollard** [comment]
@echoreos @tikkou thank you for reporting this problem! i'm happy to see that people are still using it the extension

so, there have certainly been some big issues with the extension recently. the weather API i used OpenWeatherMap limited the number of daily requests the extension can receive. therefore, the extension works for a little until we hit the limit.

thankfully, I've switched it over to a new API service, which shouldn't have this restriction. so the current version (v0.5.0) on Chrome should work fine. there are some issues with caching that are pending review, but once v0.5.1 is approved, I think the extension should be really good again!

thanks for sticking with it!

**Comment by echoreos** [comment]
i noticed the extension had me accept new perms yesterday! it's been working without an issue ever since I accepted those new perms. and no worries, i love this extension so much. i've been playing mc since the very beginning, so its def a comfort thing for me, and seeing my weather in mc screenshots just tickles that part of my brain <3

**Comment by tikkou** [comment]
recently I switched from Edge to Firefox so I didn't notice it, will the update also come to Firefox?
![imagem](https://user-images.githubusercontent.com/71342961/200970542-86b29e54-5fa5-4d05-bf95-08afcb79fad7.png)

**Comment by sawyerpollard** [comment]
@tikkou Think I just fixed it on firefox! Let me know if it works

**Comment by tikkou** [comment]
it's working
